GET http://localhost:8080/api/categories
###
POST http://localhost:8080/api/categories
Content-Type: application/json

{
  "category_id": 110,
  "name": "Obudowy",
  "subcategories": [
    {
      "subcategory_id": 309,
      "name": "ATX",
      "filters": [
        "rozmiar",
        "kompatybilnosc",
        "wentylacja"
      ]
    },
    {
      "subcategory_id": 310,
      "name": "Micro-ATX",
      "filters": [
        "rozmiar",
        "kompatybilnosc",
        "wentylacja"
      ]
    }
  ]
}

