GET http://localhost:8081/api/categories
###
POST http://localhost:8081/api/categories
Content-Type: application/json

{
  "category_id": 110,
  "name": "Obudowy",
  "subcategories": [
    {
      "subcategory_id": 309,
      "name": "ATX",
      "filters": [
        "rozmiar",
        "kompatybilnosc",
        "wentylacja"
      ]
    },
    {
      "subcategory_id": 310,
      "name": "Micro-ATX",
      "filters": [
        "rozmiar",
        "kompatybilnosc",
        "wentylacja"
      ]
    }
  ]
}
###
PUT http://localhost:8081/api/categories/676ac5dd155e1b2c46fba668
Content-Type: application/json

{
  "category_id": 111,
  "name": "laptopy",
  "subcategories": [
    {
      "subcategory_id": 409,
      "name": "ATX",
      "filters": [
        "rozmiar",
        "kompatybilnosc",
        "wentylacja"
      ]
    },
    {
      "subcategory_id": 410,
      "name": "Micro-ATX",
      "filters": [
        "rozmiar",
        "kompatybilnosc",
        "wentylacja"
      ]
    }
  ]
}
###
DELETE http://localhost:8081/api/categories/676ac5dd155e1b2c46fba668
