GET http://localhost:4000/api/orders
###
GET http://localhost:4000/api/orders/6785813e1e9d6ea3e46807c9
###
POST http://localhost:4000/api/orders
Content-Type: application/json


{

  "user_id": "676d564177648b4056eb16eb",
  "products": [
    {
      "_id": "678317465a9c6c95008b4365",
      "product_id": "677a94adaeb32b181a1eac2d",
      "quantity": 8
    }
  ],
  "status": "completed"



}
###
PUT localhost:4000/api/orders/6785813e1e9d6ea3e46807c9
Content-Type: application/json

{
      "user_id": "676d564177648b4056eb16eb",
      "products": [
        {
          "_id": "67831bab45550b63ee9d743b",
          "product_id": "677c78cbca1ba39b8d21aa56",
          "quantity": 9
        }
      ],
      "status": "pending"
    }
###
DELETE localhost:4000/api/orders/6785813e1e9d6ea3e46807c9
