GET localhost:4000/api/products
###

GET localhost:4000/api/products/678582d72c503f040722ae1a


###
POST localhost:4000/api/products/
Content-Type: application/json

{
  "name": "ada",
  "price": 479.99,
  "category_id": 105,
  "subcategory_id": 210,
  "filters": {
    "rozmiar": "Micro-ATX",
    "kompatybilnosc": "Płyty mATX, ITX",
    "wentylacja": "Optymalna"
  },
  "description": "Obudowa Komputerowa o nowoczesnym designie.",
  "stock": 50,
  "images": [
    "https://example.com/images/fractal_design_meshify_c.jpg"
  ]

}
###
PATCH localhost:4000/api/products/678582d72c503f040722ae1a/stock
Content-Type: application/json


{
  "_id": "677aec2298dd120b3b966f0",
  "name": "Obudowa komputerowa",
  "price": 479.99,
  "category_id": 105,
  "subcategory_id": 210,
  "filters": {
    "rozmiar": "Micro-ATX",
    "kompatybilnosc": "Płyty mATX, ITX",
    "wentylacja": "Optymalna"
  },
  "description": "Obudowa Komputerowa o nowoczesnym designie.",
  "stock": 50,
  "images": [
    "https://example.com/images/fractal_design_meshify_c.jpg"
  ]
}
###
DELETE localhost:4000/api/products/678582d72c503f040722ae1a
