GET localhost:8081/api/reviews
###
GET localhost:8081/api/reviews/677ee626b8f43460d8d02a7
###
PUT localhost:8081/api/reviews/677ee626b8f430460d8d02a7/edit
Content-Type: application/json

{
  "product_id": "64d8aabb1122cc34455aaaa",
  "user_id": "64d8aabb1122cc334455bbbb",
  "rating": 4.5,
  "comment": "dobry produkt!"

}

###
POST localhost:8081/api/reviews
Content-Type: application/json

{
  "product_id": "64d8aabb1122cc334455aaaa",
  "user_id": "64d8aabb1122cc334455bbbb",
  "rating": 4.5,
  "comment": "dobry produkt!"
}
###

DELETE localhost:8081/api/reviews/677ef897130c9bce6c0fafc